name: Makefile CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build and test on Linux
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22.x"

            - name: Install dependencies
              run: make go-deps

            - name: Checking code quality (formatting, linting etc.)
              run: make check

            - name: Checking code quality with golangci-lint
              uses: golangci/golangci-lint-action@v4
              with:
                  version: v1.56.2

            - name: Checking copyright and license is applied
              run: >-
                  docker run
                  -v $(pwd):/wrk -w /wrk
                  ghcr.io/google/addlicense
                  -check -c "Andre Jacobs" -l mit -ignore '.github/**' -ignore 'build/**' ./

            - name: Run unit-tests
              run: make test
